---
apiVersion: v1
kind: Secret
metadata:
  name: federation-secret
type: Opaque
data:
  uri: YW1xcHM6Ly9mZWRlcmF0aW9uOmZlZGVyYXRpb25AZmVkZXJhdGlvbi1ub2Rlcy5leGFtcGxlcy5zdmMuY2x1c3Rlci5sb2NhbAo= # encoded value of "amqps://federation:federation@federation-nodes.examples.svc.cluster.local"
---
apiVersion: rabbitmq.com/v1beta1
kind: Federation
metadata:
  name: federation-example
  namespace: rabbitmq-system
spec:
  name: "my-upstream"
  uriSecret:
    name: federation-secret
  expires: 3600000
  rabbitmqClusterReference:
    name: example-rabbit
---
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: federation-policy
  namespace: rabbitmq-system
spec:
  name: federation-policy # name of the policy
  pattern: "^amq." # policy will federate all exchanges whose names begin with "amq."
  applyTo: exchanges
  definition: # policy definition
    federation-upstream-set: all
  rabbitmqClusterReference:
    name: example-rabbit
