apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: producer
  labels:
    app: producer
spec:
  resources:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: super-stream-app-0
        image: pivotalrabbitmq/perf-test
        command: ["bash", "-c"]
        args:
        - AMQP_URI="amqp://$(cat /etc/rabbitmq-creds/username):$(cat /etc/rabbitmq-creds/password)@$(cat /etc/rabbitmq-creds/host):5672/%2f";
          bin/runjava com.rabbitmq.perf.PerfTest --uri ${AMQP_URI} --rate 100 --predeclared --exchange orders --routing-key amer
        volumeMounts:
        - name: rabbitmq-creds
          mountPath: "/etc/rabbitmq-creds"
          readOnly: true
      - name: super-stream-app-1
        image: pivotalrabbitmq/perf-test
        command: ["bash", "-c"]
        args:
        - AMQP_URI="amqp://$(cat /etc/rabbitmq-creds/username):$(cat /etc/rabbitmq-creds/password)@$(cat /etc/rabbitmq-creds/host):5672/%2f";
          bin/runjava com.rabbitmq.perf.PerfTest --uri ${AMQP_URI} --rate 100 --predeclared --exchange orders --routing-key apj
        volumeMounts:
        - name: rabbitmq-creds
          mountPath: "/etc/rabbitmq-creds"
          readOnly: true
      - name: super-stream-app-2
        image: pivotalrabbitmq/perf-test
        command: ["bash", "-c"]
        args:
        - AMQP_URI="amqp://$(cat /etc/rabbitmq-creds/username):$(cat /etc/rabbitmq-creds/password)@$(cat /etc/rabbitmq-creds/host):5672/%2f";
          bin/runjava com.rabbitmq.perf.PerfTest --uri ${AMQP_URI} --rate 100 --predeclared --exchange orders --routing-key emea
        volumeMounts:
        - name: rabbitmq-creds
          mountPath: "/etc/rabbitmq-creds"
          readOnly: true
      volumes:
      - name: rabbitmq-creds
        secret:
          secretName: billing-default-user
